# -*- coding: utf-8 -*-


circ_nombres = dict()

#https://www.servel.cl/juntas-electorales/

circ_nombres["ARICA Y PARINACOTA"] = set(["ARICA","ARICA NORTE","BELEN","CAMARONES","CODPA","GENERAL LAGOS","PUTRE","SAN MIGUEL DE AZAPA"])
circ_nombres["DE TARAPACA"] = set(["ALTO HOSPICIO","CAMIÑA","CHIAPA","COLCHANE","HUARA","IQUIQUE","MAMIÑA","PICA","POZO ALMONTE"])
circ_nombres["DE ANTOFAGASTA"] = set(["ANTOFAGASTA NORTE","ANTOFAGASTA SUR","CALAMA","CHIU CHIU","CHUQUICAMATA","MARIA ELENA","MEJILLONES","OLLAGUE","PEDRO DE VALDIVIA","QUILLAGUA","SAN PEDRO DE ATACAMA","SIERRA GORDA","SIERRA GORDA NORTE","TALTAL","TOCOPILLA","SAN PEDRO DE ATACAMA"])
circ_nombres["DE ATACAMA"] = set(["ALTO DEL CARMEN","CALDERA","CHAÑARAL","COPIAPO","DIEGO DE ALMAGRO","DOMEYKO","EL SALVADOR","EL TRANSITO","FREIRINA","HUASCO","POTRERILLOS","SAN FELIX","TIERRA AMARILLA","VALLENAR"])
circ_nombres["DE COQUIMBO"] = set(["ANDACOLLO","BARRAZA","CAIMANES","CANELA (CANELA BAJA)","CAREN","CERRILLOS DE TAMAYA","CHAÑARAL ALTO","CHELLEPIN","COMBARBALA","COQUIMBO","EL PALQUI","HURTADO","ILLAPEL","LA HIGUERA","LA SERENA","LAS COMPAÑIAS","LOS VILOS","MINCHA","MONTE PATRIA","OVALLE","PAIHUANO","PUNITAQUI","QUILIMARI","RAPEL","RIO HURTADO (SAMO ALTO)","SALAMANCA","TIERRAS BLANCAS","TONGOY","VICUÑA"])
circ_nombres["DE VALPARAISO"] = set(["AGUA SANTA","ALGARROBO","ALTO ACONCAGUA","BARON","CABILDO","CALERA","CALLE LARGA","CARTAGENA","CASABLANCA","CATAPILCO","CATEMU","CHINCOLCO","CONCON","CUNCUMEN","EL BELLOTO","EL MELON","EL PUERTO","EL QUISCO","EL TABO","FORESTAL","HIJUELAS","ISLA DE PASCUA","JUAN FERNANDEZ","LA CRUZ","LA LIGUA","LAGUNA VERDE","LIMACHE","LLAY-LLAY","LOS ANDES","MIRAFLORES","NOGALES","OLMUE","PANQUEHUE","PAPUDO","PETORCA","PLACILLA DE PEÑUELAS","PLAYA ANCHA","PUCHUNCAVI","PUTAENDO","QUILLOTA","QUILPUE","QUINTERO","RINCONADA","SAN ANTONIO","SAN ESTEBAN","SAN FELIPE","SAN PEDRO DE QUILLOTA","SANTA MARIA","SANTO DOMINGO","SAUSALITO","VILLA ALEMANA","ZAPALLAR","LOS MOLLES"])
#http://www.quilpueonline.cl/tag/circunscripcion-electoral-los-molles/
circ_nombres["METROPOLITANA DE SANTIAGO"] = set(["ALAMEDA","ALHUE","APOQUINDO","BELLAVISTA","BUIN","CALERA DE TANGO","CAPITAN AVALOS","CERRILLOS","CERRO NAVIA","CHAMPA","CHICUREO","COLINA","CONSISTORIAL","CURACAVI","EL CENTRO","EL CORTIJO","EL GOLF","EL MONTE","ESTACION LO ESPEJO","ESTADIO NACIONAL","HUECHURABA","HUELQUEN","INDEPENDENCIA","ISLA DE MAIPO","JOSE PEDRO ALESSANDRI","LA CISTERNA","LA GRANJA","LA PINTANA","LA REINA","LAMPA","LAS AMERICAS","LO BARNECHEA","LO NEGRETE","LO PRADO","LO VALLEDOR","LOS LIBERTADORES","LOS PAJARITOS","LUIS CRUZ MARTINEZ","MACUL","MAIPU","MAIPU PONIENTE","MARIA PINTO","MELIPILLA","P AGUIRRE CERDA N.","P AGUIRRE CERDA S.","PADRE HURTADO","PAINE","PARQUE ALMAGRO","PARQUE O'HIGGINS","PEÑAFLOR","PEÑALOLEN","PIRQUE","PLAZA EGAÑA","PLAZA ÑUÑOA","PROVIDENCIA","PUDAHUEL","PUDAHUEL SUR","PUENTE ALTO","QUILICURA","QUINTA NORMAL","RECOLETA NORTE","RECOLETA SUR","RENCA","SAN BERNARDO","SAN JOAQUIN","SAN JOSE DE LA ESTRELLA","SAN JOSE DE MAIPO","SAN LUIS","SAN MIGUEL","SAN PEDRO","SAN RAMON","TALAGANTE","TILTIL","TRINIDAD","VITACURA","BATUCO","VALLE GRANDE","CIUDAD DE LOS VALLES","SOTERO DEL RIO","BAJOS DE MENA","CIUDAD SATELITE"])
# Batuco, Valle Grande (Lampa); Ciudad de los Valles (Pudahuel); Sótero del Río, Bajos de Mena (Puente Alto); Ciudad Satélite (Maipú): Diario Oficial 19-ago-2015
circ_nombres["DEL LIBERTADOR BDO. O'HIGGINS"] = set(["CHEPICA","CHIMBARONGO","CODEGUA","COINCO","COLTAUCO","COYA","DOÑIHUE","GRANEROS","GULTRO","LA ESTRELLA","LAGO RAPEL (EL MANZANO)","LAS CABRAS","LITUECHE","LO MIRANDA","LOLOL","LOS LIRIOS","MACHALI","MALLOA","MARCHIGUE","MOSTAZAL","NANCAGUA","NAVIDAD","OLIVAR (ALTO)","PALMILLA","PAREDONES","PELEQUEN","PERALILLO","PEUMO","PICHIDEGUA","PICHILEMU","PLACILLA","PUENTE NEGRO","PUMANQUE","QUINTA DE TILCOCO","RANCAGUA","RANCAGUA ORIENTE","RENGO","REQUINOA","ROSARIO","SAN FERNANDO","SAN PEDRO DE ALCANTARA","SAN VICENTE","SANTA CRUZ","ZUÑIGA","ESMERALDA","LA PUNTA","BUCALEMU"])
# Esmeralda (Rengo): http://transparencia.servicioelectoral.cl/normativa/2016/DO/DO%20RES-O-262-263-264-265-266-267-268.pdf
# La Punta (Sn. Fco. de Mostazal): http://transparencia.servicioelectoral.cl/normativa/2017/RO_2709.pdf
# Bucalemu (Paredones): http://transparencia.servicioelectoral.cl/normativa/2017/RO_2710.pdf
circ_nombres["DEL MAULE"] = set(["CATILLO","CAUQUENES","CHANCO","COLBUN","COLIN","CONSTITUCION","CORINTO","CUREPTO","CURICO","EMPEDRADO","GUALLECO","HUALAÑE","HUAQUEN","HUERTA DEL MAULE","ILOCA","LA HUERTA","LICANTEN","LINARES","LLICO DE MATAQUITO","LONGAVI","LONTUE","MAULE","MOLINA","NIRIVILO","ORILLA DEL MAULE","PARRAL","PELARCO","PELLUHUE","PENCAHUE","POCILLAS","PUTU","RAUCO","RETIRO","RIO CLARO (CUMPEO)","ROMERAL","SAGRADA FAMILIA","SAN CLEMENTE","SAN JAVIER","SAN RAFAEL","SANTA OLGA","SAUZAL","TALCA","TENO","TOCONEY","VICHUQUEN","VILLA ALEGRE","VILLA PRAT","YERBAS BUENAS","MELOZAL","TRES ESQUINAS","VILCHES","DUAO"])
# Tres Esquinas (Molina) http://web.molina.cl/?page_id=3195, Vilches (San Clemente), Duao (Maule) http://www.diarioelcentro.cl/noticias/cronica/servel-define-117-locales-y-2499-mesas-receptoras-de-sufragios
#http://www.munilosalamos.cl/web/alcalde-anuncio-la-creacion-de-la-nueva-circunscripcion-electoral-antihuala/
circ_nombres["DEL BIOBIO"] = set(["ALTO BIOBIO","ANDALIEN","ANTUCO","ARAUCO","BULNES","BUSTAMANTE","CABRERO","CACHAPOAL","CAMPANARIO","CAÑETE","CARAMPANGUE","CERRO NEGRO","CHIGUAYANTE","CHILLAN","CHILLAN VIEJO","COBQUECURA","COELEMU","COIHUECO","CONCEPCION CENTRO","CONTULMO","COPIULEMU","CORONEL","CURANILAHUE","DICHATO","EL CARMEN","FLORIDA","GUARILIHUE","HUALPEN","HUALQUI","ISLA MOCHA","ISLA SANTA MARIA","LA LAJA","LAGUNILLAS","LARAQUETE","LAS CANTERAS","LEBU","LIRQUEN","LLICO","LOMAS COLORADAS","LOS ALAMOS","LOS ANGELES","LOS CERROS","LOTA","MEDIO CAMINO","MONTE AGUILA","MULCHEN","NACIMIENTO","NEGRETE","NINHUE","ÑIQUEN","PEMUCO","PENCO","PINTO","POLCURA","PORTEZUELO","PUEBLO SECO","PUENTE ÑUBLE","QUILACO","QUILLECO","QUILLON","QUINCHAMALI","QUIRIHUE","RAFAEL","RANQUIL (ÑIPAS)","RECINTO","RERE","RIO CLARO","RUCAPEQUEN","SAN CARLOS","SAN FABIAN","SAN IGNACIO","SAN NICOLAS","SAN PEDRO DE LA PAZ","SAN ROSENDO","SANTA BARBARA","SANTA CLARA","SANTA FE","SANTA JUANA","TALCAHUANO","TALCAMAVIDA","TIRUA","TOME","TOMECO","TREGUACO","TUCAPEL","TUCAPEL (HUEPIL)","VEGAS DE ITATA","YUMBEL","YUMBEL ESTACION","YUNGAY","TRUPAN","ANTIHUALA"])
#www.servel.cl/servel-abrio-circunscripciones-electorales-en-bajos-de-mena-melozal-y-trupan/
#https://www.araucaniacuenta.cl/servel-araucania-informa-de-nuevas-circunscripciones-electorales-en-la-region/
circ_nombres["DE LA ARAUCANIA"] = set(["ANGOL","BARROS ARANA","CAJON","CAPITAN PASTENE","CARAHUE","CERRO ÑIELOL","CHERQUENCO","CHOLCHOL","COLLIPULLI","COMUY","CUNCO","CURACAUTIN","CURARREHUE","ERCILLA","FREIRE","GALVARINO","GORBEA","HUALPIN","HUEQUEN","HUISCAPI","ICALMA","LABRANZA","LASTARRIA","LAUTARO","LICAN-RAY","LONCOCHE","LONQUIMAY","LOS LAURELES","LOS SAUCES","LUMACO","MELIPEUCO","MININCO","NEHUENTUE","NUEVA IMPERIAL","PADRE LAS CASAS","PAILAHUEQUE","PEDRO DE VALDIVIA (TEMUCO)","PERQUENCO","PICHIPELLAHUEN","PILLANLELBUN","PITRUFQUEN","PUCON","PUERTO DOMINGUEZ","PUREN","QUEPE","QUEULE","QUITRATUE","RADAL","RENAICO","SAAVEDRA","SAN RAMON (Padre las Casas)","SELVA OBSCURA","TEMUCO CENTRO","TEODORO SCHMIDT","TOLTEN","TRAIGUEN","TROVOLHUE","VICTORIA","VILCUN","VILLARRICA","ÑANCUL","TIJERAL","MALALCAHUELLO","LIUCURA"])
#http://www.diariolaguino.cl/noticia/politica/2015/09/localidades-de-nontuela-y-currine-tendran-sus-propias-mesas-de-votacion
#http://www.lavozdelranco.cl/?p=7907
#http://www.diariolaguino.cl/noticia/politica/2016/10/rinihue-vivio-primera-experiencia-como-local-de-votacion
#http://deurresti.cl/2015/08/17/senador-de-urresti-destaca-avances-del-servel-para-crear-nuevas-circunscripciones-electorales-en-los-rios/
circ_nombres["DE LOS RIOS"] = set(["ANTILHUE","CHOSHUENCO","COÑARIPE","CORRAL","FUTRONO","LA UNION","LAGO RANCO","LANCO","LIQUIÑE","LLIFEN","LOS LAGOS","MAFIL","MALALHUE","MANTILHUE","MARIQUINA","MEHUIN","NELTUME","NIEBLA","PAILLACO","PANGUIPULLI","PICHIRROPULLI","REUMEN","RIÑINAHUE","RIO BUENO","VALDIVIA","ISLA DEL REY","NONTUELA","CURRIÑÉ","PUERTO NUEVO","FOLILCO","RIÑIHUE","PELCHUQUÍN","CIRUELOS","CRUCERO","CAYURRUCA","LAS ANIMAS"])
#https://www.puertomontt.cl/2016/06/22/vecinos-de-lenca-chamiza-la-vara-y-huelmo-podran-votar-en-recintos-cercanos/
circ_nombres["DE LOS LAGOS"] = set(["ALERCE","ANCUD","AYACARA","BAHIA MANSA","CALBUCO","CAÑITAS","CARELMAPU","CASMA","CAS   TRO","CHACAO","CHAITEN","CHAULINEC","CHONCHI","COCHAMO","COLACO","CONTAO","CURACO DE VELEZ","DALCAHUE","ENSENADA","FRESIA","FRUTILLAR","FUTALEUFU","HUALAIHUE","HUALAIHUE PUERTO","HUEYUSCA","ISLA GUAR","ISLA MAILLEN","ISLA PULUQUI","LAS CASCADAS","LAS QUEMAS","LLANADA GRANDE","LLANQUIHUE","LOS MUERMOS","MAULLIN","MECHUQUE","METAHUE","MISION DE LA COSTA","NUEVA BRAUNAU","OSORNO","PALENA","PARGUA","PEULLA","PUELO","PUERTO MONTT","PUERTO OCTAY","PUERTO VARAS","PUQUELDON","PURRANQUE","PUYEHUE (ENTRE LAGOS)","QUEHUI","QUEILEN","QUELLON","QUEMCHI","QUENAC","QUENUIR","QUILACAHUIN","QUINCHAO (ACHAO)","RAHUE","RALUN","RIACHUELO","RILAN","RIO NEGRO","ROLECHA","SAN JUAN DE LA COSTA","SAN PABLO","TEGUALDA","TENAUN","VILLA SANTA LUCIA","LA VARA","CHAMIZA","LENCA","HUELMO","CORTE ALTO","MONTEMAR","LLIUCO"])
circ_nombres["AISEN DEL GRAL. CARLOS IBAÑEZ"] = set(["AISEN","BAHIA MURTA","BALMACEDA","CHILE CHICO","CISNES","COCHRANE","CORCOVADO","COYHAIQUE","GUAITECAS","LA JUNTA","LA TAPERA","LAGO VERDE","MAÑIHUALES","ÑIREHUAO","O'HIGGINS","PUERTO AGUIRRE","PUERTO CHACABUCO","PUERTO GUADAL","PUYUHUAPI","RIO IBAÑEZ","RIO TRANQUILO","TORTEL","VALLE SIMPSON","VILLA CERRO CASTILLO"])
circ_nombres["DE MAGALLANES Y ANTARTICA CH."] = set(["ANTARTICA","CABO DE HORNOS (NAVARINO)","LAGUNA BLANCA","NATALES","PORVENIR","PRIMAVERA","PUERTO EDEN","PUNTA ARENAS","RIO VERDE","SAN GREGORIO","TIMAUKEL","TORRES DEL PAINE (C. CASTILLO)"])

#######################################

region_nums = dict()

region_nums["DE TARAPACA"] = "1"
region_nums["DE ANTOFAGASTA"] = "2"
region_nums["DE ATACAMA"] = "3"
region_nums["DE COQUIMBO"] = "4"
region_nums["DE VALPARAISO"] = "5"
region_nums["DEL LIBERTADOR BDO. O'HIGGINS"] = "6"
region_nums["DEL MAULE"] = "7"
region_nums["DEL BIOBIO"] = "8"
region_nums["DE LA ARAUCANIA"] = "9"
region_nums["DE LOS LAGOS"] = "10"
region_nums["AISEN DEL GRAL. CARLOS IBAÑEZ"] = "11"
region_nums["DE MAGALLANES Y ANTARTICA CH."] = "12"
region_nums["METROPOLITANA DE SANTIAGO"] = "13"
region_nums["DE LOS RIOS"] = "14"
region_nums["ARICA Y PARINACOTA"] = "15"

region_nombre = {v: k for k, v in region_nums.iteritems()}

def list_circs(num_region):
	L = list(circ_nombres[region_nombre[str(num_region)]])
	L.sort()
	print "\n".join(L)

